### ISSUE TITLE
`changelist_actions` doesn't execute related method in 1.1.0

### ISSUE THREAD

**Issue by matmarczak** [crccheck/django-object-actions#103] opened 2019-11-12 10:07 UTC
I tried to setup `changelist_action` but found that related method is not executed. One can reproduce that using demo app version with docker (1.9 and 2.0) and click on `DELETE_ALL` button in `Choices` model. "just kidding!" message is not showed. It works fine in 1.0.0.

**Comment by crccheck** [comment] 2019-11-12 21:07
So it's broken in Django versions < 2.1?

**Comment by crccheck** [comment] 2019-11-12 21:09
This is probably fixed in 1.1.1 but PyPI changed their Restructructured text processing and it broke my publish. 
Duplicate of #96 ?

**Comment by crccheck** [comment] 2019-11-15 03:56
I redid the readme and got a publish working. Try version 1.1.2

**Closed** 2019-12-03 04:53 UTC
